# -*- coding: utf-8 -*-
"""Flask IPL Winners API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sF4VtOoqIPHQQs2nJ_GjebYbuEHaSQl
"""

from flask import Flask, jsonify

app = Flask(__name__)

# Data for IPL winners for the last 5 years (as of mid-2025 based on search results)
# Please note: The search results provided data up to IPL 2025.
# If you are in a different year, you might need to update this data.
IPL_WINNERS = [
    {"year": 2025, "winner": "Royal Challengers Bengaluru"},
    {"year": 2024, "winner": "Kolkata Knight Riders"},
    {"year": 2023, "winner": "Chennai Super Kings"},
    {"year": 2022, "winner": "Gujarat Titans"},
    {"year": 2021, "winner": "Chennai Super Kings"}
]

@app.route('/')
def home():
    """
    Home endpoint.
    Returns a welcome message and instructions to get IPL winners.
    """
    return jsonify({
        "message": "Welcome to the IPL Winners API!",
        "instructions": "Navigate to /ipl-winners to get the list of IPL winners for the last 5 years."
    })

@app.route('/ipl-winners', methods=['GET'])
def get_ipl_winners():
    """
    Endpoint to get IPL winners for the last 5 years.
    Returns a JSON array of winner objects.
    """
    return jsonify(IPL_WINNERS)

if __name__ == '__main__':
    # When deploying to Elastic Beanstalk, you'll typically use a WSGI server like Gunicorn.
    # For local testing, you can run: python application.py (or whatever you name this file)
    app.run(debug=True, host='0.0.0.0', port=5000)